//! Core authorization model: principals, registrations, grants, roles, and
//! the service-graph policy consumed from topology artifacts.

use std::collections::{BTreeMap, BTreeSet};

use ras_authorization_token::PrincipalKind;
use serde::{Deserialize, Serialize};

/// A principal that can hold grants and request tokens.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Principal {
    User { user_id: String },
    Service { service_id: String },
    ServiceAccount { service_account_id: String },
    Application { application_id: String },
}

impl Principal {
    /// The token-claims principal kind for this principal.
    pub fn principal_kind(&self) -> PrincipalKind {
        match self {
            Principal::User { .. } => PrincipalKind::User,
            Principal::Service { .. } => PrincipalKind::Service,
            Principal::ServiceAccount { .. } => PrincipalKind::ServiceAccount,
            Principal::Application { .. } => PrincipalKind::Application,
        }
    }

    /// The principal's identifier (token `sub`).
    pub fn id(&self) -> &str {
        match self {
            Principal::User { user_id } => user_id,
            Principal::Service { service_id } => service_id,
            Principal::ServiceAccount { service_account_id } => service_account_id,
            Principal::Application { application_id } => application_id,
        }
    }
}

/// A registered internal service.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ServiceRegistration {
    /// Stable service id; the `sub` of tokens the service requests.
    pub service_id: String,
    pub display_name: String,
    /// The audience this service validates on inbound tokens.
    pub audience: String,
    /// Disabled services can neither prove identity nor be issued tokens.
    pub enabled: bool,
}

/// One audience-scoped permission: "permission P at audience A".
///
/// Grants are always scoped by target audience — `invoice:read` granted for
/// `invoice-service` says nothing about `invoice:read` at any other
/// audience.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct AudiencePermission {
    pub audience: String,
    pub permission: String,
}

impl AudiencePermission {
    pub fn new(audience: impl Into<String>, permission: impl Into<String>) -> Self {
        Self {
            audience: audience.into(),
            permission: permission.into(),
        }
    }
}

/// A named, reusable set of audience-scoped permissions.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RoleDefinition {
    pub role_id: String,
    pub permissions: BTreeSet<AudiencePermission>,
}

/// Resolved permissions for a principal, grouped by audience.
pub type ResolvedPermissions = BTreeMap<String, BTreeSet<String>>;

/// Allowed service-to-service edges, typically generated by the topology
/// crate (#15). When loaded into the issuer, service-principal token
/// issuance outside the declared graph fails closed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ServiceGraphPolicy {
    /// Artifact schema version.
    pub schema_version: u32,
    /// The topology this policy was generated from.
    pub topology_name: String,
    /// Stable artifact id for audit trails.
    pub policy_id: String,
    /// Declared edges.
    pub edges: Vec<ServiceEdge>,
}

/// One allowed caller→audience edge with its permission ceiling.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ServiceEdge {
    /// Calling service id.
    pub caller_service_id: String,
    /// Target service audience.
    pub target_audience: String,
    /// Permissions this edge may carry. Issuance requests outside this set
    /// fail even if a broader grant exists.
    pub permissions: BTreeSet<String>,
}

impl ServiceGraphPolicy {
    /// Find the edge for a caller→audience pair.
    pub fn edge(&self, caller_service_id: &str, target_audience: &str) -> Option<&ServiceEdge> {
        self.edges.iter().find(|edge| {
            edge.caller_service_id == caller_service_id && edge.target_audience == target_audience
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn principal_kind_and_id_map_per_variant() {
        let principal = Principal::Service {
            service_id: "billing".to_string(),
        };
        assert_eq!(principal.principal_kind(), PrincipalKind::Service);
        assert_eq!(principal.id(), "billing");

        let user = Principal::User {
            user_id: "alice".to_string(),
        };
        assert_eq!(user.principal_kind(), PrincipalKind::User);
        assert_eq!(user.id(), "alice");
    }

    #[test]
    fn policy_edge_lookup_matches_caller_and_audience() {
        let policy = ServiceGraphPolicy {
            schema_version: 1,
            topology_name: "internal-tools".to_string(),
            policy_id: "internal-tools@1".to_string(),
            edges: vec![ServiceEdge {
                caller_service_id: "billing".to_string(),
                target_audience: "invoice-service".to_string(),
                permissions: BTreeSet::from(["invoice:read".to_string()]),
            }],
        };
        assert!(policy.edge("billing", "invoice-service").is_some());
        assert!(policy.edge("billing", "admin-service").is_none());
        assert!(policy.edge("admin", "invoice-service").is_none());
    }
}
